#[cfg(test)]
mod tests {
    use zz_validator::token::{ Token, tokenize };
    #[test]
    fn test_tokenize_full_dsl_with_scientific_range() {
        let dsl =
            r#"
        (
            username:string[3,20] regex("^[a-zA-Z0-9_]+$"),  
            age:int[0,150]=30,      
            age:int=30,    
            score:float(0,100),                        
            active:bool=true,                    
            nickname?:string[0,20],
            role:string enum("admin","user","guest")=user,  
            id:int|float,                              
            profile:object(
                first_name:string[1,50],
                last_name:string[1,50],
                contact:object(
                    email:string regex("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"),
                    phone?:string[0,20]
                )
            ),

            tags:array<string[1,10]>,            
            scores:array<int[0,100]>,

            distance:float[1.47e11,1.52e11]=1.496e11,
            positive_scientific:float[+1.0e3,+2.0E3]=+1.5e3, 
            negative_scientific:float[-1.0e3,-2.0E3]=-1.5e3, 
            mixed_sign_scientific:float[-1.0e3,+2.0e3]=3.0e0,
            escaped_field:string regex("line1\nline2\rtab\tquote\"backslash\\"),
            _start_with_underscore:string[1,10]=5
        )
        "#;

        let tokens = tokenize(dsl).expect("Failed to tokenize DSL");

        let expected_tokens = vec![
            Token::LParen,
            Token::Ident("username".into()),
            Token::Colon,
            Token::Ident("string".into()),
            Token::LBracket,
            Token::Number("3".into()),
            Token::Comma,
            Token::Number("20".into()),
            Token::RBracket,
            Token::Ident("regex".into()),
            Token::LParen,
            Token::Ident("^[a-zA-Z0-9_]+$".into()),
            Token::RParen,
            Token::Comma,

            Token::Ident("age".into()),
            Token::Colon,
            Token::Ident("int".into()),
            Token::LBracket,
            Token::Number("0".into()),
            Token::Comma,
            Token::Number("150".into()),
            Token::RBracket,
            Token::Equal,
            Token::Number("30".into()),
            Token::Comma,

            Token::Ident("age".into()),
            Token::Colon,
            Token::Ident("int".into()),
            Token::Equal,
            Token::Number("30".into()),
            Token::Comma,

            Token::Ident("score".into()),
            Token::Colon,
            Token::Ident("float".into()),
            Token::LParen,
            Token::Number("0".into()),
            Token::Comma,
            Token::Number("100".into()),
            Token::RParen,
            Token::Comma,

            Token::Ident("active".into()),
            Token::Colon,
            Token::Ident("bool".into()),
            Token::Equal,
            Token::Ident("true".into()),
            Token::Comma,

            Token::Ident("nickname".into()),
            Token::Question,
            Token::Colon,
            Token::Ident("string".into()),
            Token::LBracket,
            Token::Number("0".into()),
            Token::Comma,
            Token::Number("20".into()),
            Token::RBracket,
            Token::Comma,

            Token::Ident("role".into()),
            Token::Colon,
            Token::Ident("string".into()),
            Token::Ident("enum".into()),
            Token::LParen,
            Token::Ident("admin".into()),
            Token::Comma,
            Token::Ident("user".into()),
            Token::Comma,
            Token::Ident("guest".into()),
            Token::RParen,
            Token::Equal,
            Token::Ident("user".into()),
            Token::Comma,

            Token::Ident("id".into()),
            Token::Colon,
            Token::Ident("int".into()),
            Token::Pipe,
            Token::Ident("float".into()),
            Token::Comma,

            Token::Ident("profile".into()),
            Token::Colon,
            Token::Ident("object".into()),
            Token::LParen,
            Token::Ident("first_name".into()),
            Token::Colon,
            Token::Ident("string".into()),
            Token::LBracket,
            Token::Number("1".into()),
            Token::Comma,
            Token::Number("50".into()),
            Token::RBracket,
            Token::Comma,
            Token::Ident("last_name".into()),
            Token::Colon,
            Token::Ident("string".into()),
            Token::LBracket,
            Token::Number("1".into()),
            Token::Comma,
            Token::Number("50".into()),
            Token::RBracket,
            Token::Comma,
            Token::Ident("contact".into()),
            Token::Colon,
            Token::Ident("object".into()),
            Token::LParen,
            Token::Ident("email".into()),
            Token::Colon,
            Token::Ident("string".into()),
            Token::Ident("regex".into()),
            Token::LParen,
            Token::Ident("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$".into()),
            Token::RParen,
            Token::Comma,
            Token::Ident("phone".into()),
            Token::Question,
            Token::Colon,
            Token::Ident("string".into()),
            Token::LBracket,
            Token::Number("0".into()),
            Token::Comma,
            Token::Number("20".into()),
            Token::RBracket,
            Token::RParen,
            Token::RParen,
            Token::Comma,

            Token::Ident("tags".into()),
            Token::Colon,
            Token::Ident("array".into()),
            Token::Lt,
            Token::Ident("string".into()),
            Token::LBracket,
            Token::Number("1".into()),
            Token::Comma,
            Token::Number("10".into()),
            Token::RBracket,
            Token::Gt,
            Token::Comma,

            Token::Ident("scores".into()),
            Token::Colon,
            Token::Ident("array".into()),
            Token::Lt,
            Token::Ident("int".into()),
            Token::LBracket,
            Token::Number("0".into()),
            Token::Comma,
            Token::Number("100".into()),
            Token::RBracket,
            Token::Gt,
            Token::Comma,

            // 新增科学计数法
            Token::Ident("distance".into()),
            Token::Colon,
            Token::Ident("float".into()),
            Token::LBracket,
            Token::Number("1.47e11".into()),
            Token::Comma,
            Token::Number("1.52e11".into()),
            Token::RBracket,
            Token::Equal,
            Token::Number("1.496e11".into()),
            Token::Comma,

            Token::Ident("positive_scientific".into()),
            Token::Colon,
            Token::Ident("float".into()),
            Token::LBracket,
            Token::Number("+1.0e3".into()),
            Token::Comma,
            Token::Number("+2.0E3".into()),
            Token::RBracket,
            Token::Equal,
            Token::Number("+1.5e3".into()),
            Token::Comma,

            Token::Ident("negative_scientific".into()),
            Token::Colon,
            Token::Ident("float".into()),
            Token::LBracket,
            Token::Number("-1.0e3".into()),
            Token::Comma,
            Token::Number("-2.0E3".into()),
            Token::RBracket,
            Token::Equal,
            Token::Number("-1.5e3".into()),
            Token::Comma,

            Token::Ident("mixed_sign_scientific".into()),
            Token::Colon,
            Token::Ident("float".into()),
            Token::LBracket,
            Token::Number("-1.0e3".into()),
            Token::Comma,
            Token::Number("+2.0e3".into()),
            Token::RBracket,
            Token::Equal,
            Token::Number("3.0e0".into()),
            Token::Comma,

            Token::Ident("escaped_field".into()),
            Token::Colon,
            Token::Ident("string".into()),
            Token::Ident("regex".into()),
            Token::LParen,
            Token::Ident("line1\nline2\rtab\tquote\"backslash\\".into()),
            Token::RParen,
            Token::Comma,

            // field_with_underscore
            Token::Ident("_start_with_underscore".into()),
            Token::Colon,
            Token::Ident("string".into()),
            Token::LBracket,
            Token::Number("1".into()),
            Token::Comma,
            Token::Number("10".into()),
            Token::RBracket,
            Token::Equal,
            Token::Number("5".into()),

            Token::RParen
        ];

        assert_eq!(tokens, expected_tokens, "Tokens did not match expected sequence");
    }
}
